# Generated by Django 6.1 on 2026-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scam_flags',
            field=models.TextField(blank=True),
        ),
    ]
