# Generated by Django 6.1 on 2026-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_scam_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scam_flags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
