# Generated by Django 6.1 on 2026-08-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_scam_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('email', 'Email'), ('external_link', 'External Link')], default='external_link', max_length=20),
        ),
    ]
