# Generated by Django 6.1 on 2026-08-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_application_email_job_application_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('sent', 'Sent'), ('dismissed', 'Dismissed')], default='draft', max_length=20)),
                ('application_method', models.CharField(choices=[('email', 'Email'), ('external_link', 'External Link')], max_length=20)),
                ('application_email', models.EmailField(blank=True, default='', max_length=254)),
                ('generated_cv', models.FileField(upload_to='applications/cvs/')),
                ('generated_cover_letter', models.FileField(upload_to='applications/cover_letters/')),
                ('email_subject', models.CharField(blank=True, default='', max_length=255)),
                ('email_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
